### PR TITLE
use require_relative to enable non-gem access

### PR DESCRIPTION
**Pull request by sunito**

### CODE REVIEW

**Comment by sunito** [comment]
Any comments/reviews?
To me, this seems to be a straightforward fix to make the library work outside of the Rubgems environment.

**Comment by DRMacIver** [comment]
Hi @sunito. Sorry for the delay replying!

The ruby component is currently in a partial state of getting it up and running in the current build, which means we can't currently merge pull requests to it at present. I'm hoping to get this resolved by the end of the week.

I don't have a problem with this change, but could you elaborate on the use case? How are you installing the library if not with rubygems?

**Comment by sunito** [comment]
Hello @DRMacIver, 
thanks for the explanation. There is no hurry, getting it running within a week is absolutely fine with me.

I use hypothesis as a git clone in the /opt folder. Mainly in order to get myself ready for some (more substatial ;) ) pull requests.

**Comment by DRMacIver** [comment]
Hi @sunito. Sorry for the delay in letting you know, but we're once more open for pull requests on Hypothesis for Ruby (yay!).

To get this ready to be merged you'll need to write a release file (and bring it up to date with master). This is a file called `RELEASE.md` that lives in the root of the `hypothesis-ruby` directory and specifies the release type (in this case patch). The process is [described a bit more here](https://github.com/HypothesisWorks/hypothesis/blob/29b5bbac47182ecaecd124c9a881e1eaad8ba1c3/guides/documentation.rst#changelog-entries) (it says `RELEASE.rst` rather than `RELEASE.md`. We need to update that - `hypothesis-python` uses rst, but everything else is markdown).

Let me know if you have any questions about the process! And once again sorry for the delay on this. Hopefully should be an anomaly now that we've got the system actually working.

**Comment by Zac-HD** [comment]
Hi @sunito - are you planning to come back to this?  If so, you'll just need to rebase on master to get up to date, then add `RELEASE.md` as David mentioned before we can merge!

**Comment by Zac-HD** [comment]
Closing due to inactivity.

**Comment by sunito** [comment]
OK, I've submitted a new PR.

**Pull request closed without merging**
