### PR TITLE
New dragonfly logo!

### LINKED ISSUE #1519: New Hypothesis Dragonfly branding
:wave: 
@Zac-HD 
I have volunteered myself to create some new branding for hypothesis as the current 'limited edition' branding is not Hypothesis' intellectual property. I've created a couple of sketches of a dragonfly that might work and am beginning to do some rough vectors of them for use. Please provide feedback if you have any! I only have a few hours i can dedicate to it today during the sprint so hopefully i can get something completed by then. If not i'll be working on it off-and-on probably for the net week. 
Below are some preliminary sketches: 

img_2174

Thanks in advance for your input!

### PR DESCRIPTION
**Pull request by Zac-HD**
Closes #1519, with many thanks to @libbyberrie :sparkling_heart: 

@DRMacIver: you're the only one with admin powers to update the GH org image to `dragonfly-rainbow-svg`  (and the `hypothesis.works` links from the repo and org page to use HTTPS :lock:)

And for opinion: should stickers (, badges, etc) include the word `Hypothesis` or a link to make the branding more obvious?  I'm inclined to say yes, which opens a host of questions about fonts...

### CODE REVIEW

**Comment by libbyberrie** [comment]
Thanks everyone for there patience with this when i dropped off the face of the planet ❤️ 
As for fonts, I can provide a couple of suggestions, but take all of them with a grain of salt: 

[Lato](https://fonts.google.com/specimen/Lato)is a clean, readable choice, if a little overused (was previous Slack logotype).
[Mallana](https://fonts.google.com/specimen/Mallanna) Nice round ends, A nice branding/display font but less legible as full paragraphs. 
[Anaheim](https://fonts.google.com/specimen/Anaheim) is an OK slabbed option but wouldn't recommend for whole paragraphs. 
[M PLUS Rounded 1C](https://fonts.google.com/specimen/M+PLUS+Rounded+1c) is a nice display font and kind of reminds me of early 2000s interpretations of the future somehow? So i have a nostalgia-based attachment to it. Not sure it's the look that you want to go for but 'Hypothesis' looks nice in it. Some kerning/tracking adjustments might be needed.

**Comment by Zac-HD** [comment]
They all look great, but apparently I have a soft spot for rounded ends!  

...it sounds like you might be up for designing our stickers with the dragonfly (mascot name TBD I guess?) and `Hypothesis` M PLUS Rounded 1C (medium weight?).  Interested?

**Comment by libbyberrie** [comment]
I am, but i'm also time-poor 😂 
What's your timeframe?

**Comment by Zac-HD** [comment]
Within a month or so?  We can merge this and add a sticker image later 😄

**Comment by Zac-HD** [comment]
Hmm.  I've just tried doing an import-export through GIMP and all my local image viewers (and Chrome!) are happy with the local copy, but it seems to be somehow invalid on upload.  Downloading the version, windows image viewer says it's "damaged, corrupted, or too large"... but it's bitwise identical to the "good" version.

Basically I'd give up, happy to include or remove it as people prefer.

**Comment by alexwlchan** [comment]
I have no time to dig in tonight, but colour me amused that even the Hypothesis *logo* seems to be finding software bugs!

**Comment by DRMacIver** [comment]
🎉 

This looks great. Thank you, once again!

Boring admin details on our end to note for future reference:

* Github does not accept svg profile pictures. Sad face. I did a manual conversion via gimp.
* Github insisted on cropping it slightly. I did my best to make the crop good.
* I have no idea what's going on with the favicon. I'm going to pretend the problem doesn't exist and hope reality comes around to my point of view.

We may wish to automate some of this if we find ourselves changing the logo again (even in minor ways) but for now I think having done it manually is fine.

**Pull request merged**
