### PR TITLE
Remove references to RSpec.

### PR DESCRIPTION
**Pull request by amw-zero**
It doesn't look like any RSpec code is actually invoked in the codebase, and requiring these files prevents using hypothesis-ruby with different test runners (i.e. Minitest).

Minitest is the default test runner with Rails, and supporting it would be great. I don't see a compelling reason to limit hypothesis-ruby to RSpec alone.

### CODE REVIEW

**Review by Zac-HD — APPROVED** [review]
Nice!  If there's a nice way to *test* that it works with e.g. Minitest that would be great; otherwise I'm happy to merge as-is 😄

**Comment by amw-zero** [comment]
Good point, I'll work on that. Part of the reason this happened is that both `RSpec` and `Minitest` are local dependencies of the gem code, so they are both present during development. This hides the fact that the Minitest tests don't actually work in isolation - there may be a way to expose that in the tests.

**Comment by Stranger6667** [comment]
There is also [a note](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-ruby/docs/debt.md#stable-identifiers-from-rspec) on RSpec in the docs (not sure how relevant this note is, though) - probably that section should be revisited as well.

**Comment by amw-zero** [comment]
Re the note about RSpec - I think it's still accurate actually. The code is still [parsing the result of `inspect`](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-ruby/lib/hypothesis.rb#L82-L87) to get this stable identifier. My interpretation of that note is that the handling of that is bad for RSpec alone - the code has a really clean way of getting a stable id [for Minitest](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-ruby/lib/hypothesis.rb#L54-L59).

**Comment by amw-zero** [comment]
Running the RSpec and Minitest tests separately allowed me to control which libraries are loaded during each test suite. Running the Minitest suite without RSpec loaded caught this bug - that was the best way that I could come up with for testing this.

**Pull request merged**
