### PR TITLE
pylint fixes

### PR DESCRIPTION
**Pull request by marksmayo**
Fixes to a bunch of pylint warnings/fixes

### CODE REVIEW

**Comment by marksmayo** [comment]
Hmm, looks like a problem in the .tox folder, which I didn't modify...looking into it

**Comment by marksmayo** [comment]
Duh, generated code from my code. Fixed typo.

**Comment by Zac-HD** [comment]
I'm really sorry about this, because I can tell that this was a lot of work and I really appreciate that, but I don't think we can accept this PR 😥 

Many of these changes are following rules which make sense in the abstract, but make the code harder to read (e.g. some of the `else` removals, removals of some parens), and others actually change the meaning of the code in ways that we don't want (e.g. changing `x == []` to `not x` is a semantic change, and we often *want* the former).  In many more cases, I just don't think it's worth the code churn and extra steps when searching through the git history.

If you're keen to contribute, I'd be delighted if you wanted to pick up an existing issue - #3478, #3131, or #3468 are good ones to start with, that don't require too much Hypothesis experience.  

Again, apologies and thank you so much for the work you've clearly put in!

**Comment by marksmayo** [comment]
:( :(

No that's ok, I totally get the reasoning.  Might have a gander at the existing ones! :)

**Comment by Zac-HD** [comment]
❤️

**Pull request closed without merging**
