### PR TITLE
Finish migration to GitHub Actions

### PR DESCRIPTION
**Pull request by sobolevn**
Refs #2729

### CODE REVIEW

**Comment by sobolevn** [comment]
Снимок экрана 2021-01-02 в 13 03 55

Beautiful 🤩

**Comment by Zac-HD** [comment]
1. *Holy %&#$, that's fast!*
2. 20x speedup?  Wait a second...
2. Oh, right, we skip the "run the tests" part if there are no source changes.
3. Still faster, but hard to tell by how much 🙂

**Comment by Zac-HD** [comment]
OK, the automatic releases now come from Actions (🎉 at last!), so if you rebase and add caching I'll review and merge in the morning 😁

**Comment by Zac-HD** [comment]
Rebased and cherry-picked as 4123edab59d550139a3ab1291d9b78e247ba0e1c 😄

**Pull request closed without merging**
