### PR TITLE
Initial cache implementation

### LINKED ISSUE #2729: Add caching to GitHub Actions for speed
We have now merged our GitHub Actions config, and it's working well so far - but we're not quite done yet.

- [x] set up secrets in the repo settings, so that GitHub Actions can push releases to GitHub and PyPI
- [x] remove Travis config file and webhooks
- [ ] add caching for performance (@sobolevn volunteered)

### PR DESCRIPTION
**Pull request by sobolevn**
Interest points:
- I found out that I am not familiar with how Windows works
- The commit is not signed (if that's important), because I was testing out #2735 I verify that it is still me 🙂 

Closes #2729

### CODE REVIEW

**Comment by sobolevn** [comment]
Ok, something is not working as it should: https://github.com/HypothesisWorks/hypothesis/pull/2736/checks?check_run_id=1643190995

> Post job cleanup.
> Unable to reserve cache with key deps-ubuntu-3.8--5acaed87b70c35b8d9d13ae317878f539a5109b04aef90f484aa95dac61396b1, another job may be creating this cache.

**Comment by sobolevn** [comment]
Now it works:

```
Received 821454 of 9210062 (8.9%), 0.8 MBs/sec
Received 9210062 of 9210062 (100.0%), 6.7 MBs/sec
Cache Size: ~9 MB (9210062 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/2db93f54-b448-4c01-a7b9-3d5adecbf97c/cache.tzst -P -C /home/runner/work/hypothesis/hypothesis
Cache restored from key: deps-Linux-3.8-5acaed87b70c35b8d9d13ae317878f539a5109b04aef90f484aa95dac61396b1-lint
```

https://github.com/HypothesisWorks/hypothesis/pull/2736/checks?check_run_id=1643365234#step:4:14

Only windows is left.

**Comment by Zac-HD** [comment]
Re: what to cache, I think from https://github.com/HypothesisWorks/hypothesis/blob/master/tooling/scripts/common.sh that we should cache `~/.cache` (not `~/.cache/pip`).  At the moment we're downloading everything and rebuilding wheels because they're not in the cache!

**Comment by sobolevn** [comment]
I have done my best for Win support 🥇
I am sure that it can be still improved further by someone more familiar with Windows.

**Comment by Zac-HD** [comment]
OK, Linux is working and it's a fair bit faster (🎉) but we seem to have the wrong paths for Windows and OSX... under e.g. `Collecting virtualenv` we see `Downloading` rather than `Using cached virtualenv` 🤔

For Windows `c:\users\runneradmin\appdata\local\pip\cache` seems promising, and for OSX let's just leave caching disabled for now - it's not one of our slowest jobs so caching it wouldn't improve latency anyway.

**Comment by Zac-HD** [comment]
Sanity check:  Before caching, `linux-check-py39` took 215 seconds from start to executing `pytest`; afterwards it took just 49 seconds.  Saving almost three minutes per Linux job is a big win!

Windows jobs have a lot less setup code - we're only saving the time to download and build wheels, whereas Linux is compiling Python.  So here we only save eleven seconds... because it's doing less work in the first place.

**Review by Zac-HD — APPROVED** [review]
Looks good to me 🚀 

@sobolevn - after you've checked my commits, please feel free to merge!

**Comment by sobolevn** [comment]
@Zac-HD that's my first merge 😊 

Looks like you are using `Merge pull request` as a default strategy. Am I right?

**Comment by Zac-HD** [comment]
Woohoo!  Yep, I generally default to "Merge pull request", or occasionally squash-merging for e.g. Pyup's PRs where the bot does every line as a separate commit 😅

**Comment by Zac-HD** [comment]
🎉

**Comment by sobolevn** [comment]
I will now work on Codespaces support in lazy mode (we have Christmas tomorrow in Russia 🎄), thanks again!

**Comment by Zac-HD** [comment]
Merry Christmas!  Seems like a good plan to celebrate after 2020 is over 😜

**Pull request merged**
