### PR TITLE
Add `allow_subnormal` passthrough to `strategies.numpy.from_dtype()` for complex values

### PR DESCRIPTION
**Pull request by felixdivo**
I think this was just forgotten.

Related to  #3468.

### CODE REVIEW

**Comment by felixdivo** [comment]
Does this need any tests? `hypothesis-python/tests/numpy/*` never mentiones `allow_subnormal` in the test files.

**Comment by honno** [comment]
I think you're right we forgot about this, or at least thought it was low-prio at the time given "subnormal complex numbers" is something hopefully no one has to think about haha. Thanks for your contribution!

> Does this need any tests? `hypothesis-python/tests/numpy/*` never mentiones `allow_subnormal` in the test files.

I think generally we need tests for subnormal support in `extra.numpy`... but it's pretty annoying to test, as I don't think we can realistically test for both FTZ and non-FTZ scenarios on the same run of tests :sweat_smile: In any case, for `extra.array_api` we have

https://github.com/HypothesisWorks/hypothesis/blob/39e3fba78ed675733d5c405cef0c6db80c4818db/hypothesis-python/tests/array_api/test_arrays.py#L492-L511

and

https://github.com/HypothesisWorks/hypothesis/blob/39e3fba78ed675733d5c405cef0c6db80c4818db/hypothesis-python/tests/array_api/test_from_dtype.py#L92-L107

(FYI `flushes_to_zero()` checks if NumPy is flushing to zero at the time, where `xp` would be `np`, and `xps` would be `hypothesis.extra.numpy` (`nps`))

Feel free to take a stab at copying these tests, and extending them for complex numbers too, but I'll try to sit down and properly think about this over the weekend.

**Comment by felixdivo** [comment]
> "subnormal complex numbers" is something hopefully no one has to think about haha

I also hope so 😆

I'm honestly not too eager to add the tests for this ... 😅 If you will have a look anyways, then I will cowardly retreat here.

**Comment by Zac-HD** [comment]
Seconding @honno  here, I think we just forgot 😅.  And in case our pretty pedantic review process made you wonder, we really deeply appreciate all your PRs!  Thanks so much for helping us to improve Hypothesis 😍

**Comment by felixdivo** [comment]
😁 Nice! Your framework is awesome btw! It's an honour to contribute to it. You aim of "pushing software quality" of the Python ecosystem may sound a bit ambitious but I think it aptly describes your impact. 🥳 

And yeah, just a few weeks ago I realized that I'd need complex numbers in my research (never would have expected that) and was suprised how much support for it was already lurking in python, hypothesis, numpy, pytorch, ... So I figures I'd do the "last" steps here for everyone to be able to fully use it in my project for testing some numerical algorithms.

**Comment by felixdivo** [comment]
I'm a bit confused regarding the `hypothesis-python/RELEASE.rst` merge conflict: Should I resolve it by putting my changes in that file only?

**Comment by honno** [comment]
> I'm a bit confused regarding the `hypothesis-python/RELEASE.rst` merge conflict: Should I resolve it by putting my changes in that file only?

Yeah the auto-release process messed up somehow as `RELEASE.rst` shouldn't be in the main repo, so you can leave this file be for now.

**Comment by felixdivo** [comment]
Once this is merged, I'll add the pass-through of `width`, `min_magnitude` & `max_magnitude`.

**Comment by felixdivo** [comment]
Once this is merged, I'll add the pass-through of `width`, `min_magnitude` & `max_magnitude`.

**Comment by honno** [comment]
> I'll try to sit down and properly think about this over the weekend.

Had something come up so just to say I'll have another go this weekend :sweat_smile:

**Comment by honno** [comment]
So I introduced basic tests in `test_from_dtype` for subnormal validation, which I think are satisfactory. Ideally we'd have something to test FTZ builds of NumPy ala [`tests/array_api/test_array.py::test_subnormal_elements_validation`](https://github.com/HypothesisWorks/hypothesis/blob/39e3fba78ed675733d5c405cef0c6db80c4818db/hypothesis-python/tests/array_api/test_arrays.py#L492-L511), but it seems mute given we're not going to test this on CI or expect users/ourselves to have to work out how to build FTZ NumPy (where in the `array_api` case, my default local build of CuPy had FTZ float32s so I could test this easily).

I noticed this PR currently doesn't update the follow validation logic in our array strategy to also work with complex numbers

https://github.com/HypothesisWorks/hypothesis/blob/956684c08ad2fa59fa1990e4c77d820222ab8c2e/hypothesis-python/src/hypothesis/extra/numpy.py#L212

Would be nice to update this, will explore myself. We also didn't update this behaviour for `extra.array_api`...

**Comment by felixdivo** [comment]
>So I introduced basic tests in test_from_dtype for subnormal validation, which I think are satisfactory.

Nice! 🧑‍🔬 

> noticed this PR currently doesn't update the following helpful error logic for FTZ subnormal behaviour

That's true, but isn't that already handled by the function, since it eventually calls `floats()` anyways? And `floats()` does the following:

https://github.com/HypothesisWorks/hypothesis/blob/956684c08ad2fa59fa1990e4c77d820222ab8c2e/hypothesis-python/src/hypothesis/strategies/_internal/numbers.py#L446-L478

I'm honestly not too much into this, for me it already looked like it was working fine. 😅

**Review by Zac-HD — APPROVED** [review]
Thanks again @felixdivo!

**Pull request merged**
