### PR TITLE
Updates Python versions to newer ones

### PR DESCRIPTION
**Pull request by sobolevn**
It is time to update the tooling with new security releases 🔐

### CODE REVIEW

**Review by Zac-HD — APPROVED** [review]
LGTM

**Comment by Zac-HD** [comment]
I've been idly wondering about automating this as part of our weekly dependency update job... it's low enough priority that I haven't done anything, since I'm also unconvinced that maintaining the script (for eg EOL and prerelease pythons) would actually be less effort than doing it by hand. Maybe just a helper to report the latest versions available from pyenv?

**Comment by sobolevn** [comment]
We can try to reuse this Action: https://github.com/wemake-services/wemake-python-styleguide/blob/master/.github/workflows/depup.yml#L12-L18

**Comment by Zac-HD** [comment]
We already have the actions part working - we'd just need to drop some python code in https://github.com/HypothesisWorks/hypothesis/blob/9e34e289ee533c08ef7eefa80206ee33ed60710f/tooling/src/hypothesistooling/__main__.py#L261-L269

which bumps the Python versions.

**Comment by sobolevn** [comment]
@Zac-HD Thanks! Do you want to include some extra infra code in this PR or can I merge it?

**Comment by Zac-HD** [comment]
Merge away! As I said above, automating this is low priority.

**Pull request merged**
