### PR TITLE
Generate URL fragments

### PR DESCRIPTION
**Pull request by paxcodes**
All tests under `hypothesis-python/tests/cover/test_provisional_strategies.py` currently pass.

Still thinking about allowing non-encoded "/" and "?" for fragments.

Fixes https://github.com/HypothesisWorks/hypothesis/issues/2908

### CODE REVIEW

**Review by Zac-HD — COMMENTED** [review]
Looks good!  The main points are to add yourself to the alphabetised list in `AUTHORS.rst`, and to create a `hypothesis-python/RELEASE.rst` with e.g. 

```rst
RELEASE_TYPE: minor

This release adds URL fragment generation to the :func:`~hypothesis.provisional.urls`
strategy (:issue:`2908`).  Thanks to Rosalyn Pax for contributing this patch at the
`PyCon US Mentored Sprints <https://us.pycon.org/2021/summits/mentored-sprints/>`__!

**Comment by paxcodes** [comment]
I added a separate encode function for the fragments so it doesn't encode "?" and "/"

Some thoughts:

- This will not generate fragments that have encoded “?” and “/“ , which should still be a valid fragment —— should I put in some “randomizer” so that sometimes it encodes it and sometimes it doesn’t? Not sure if this is the Pythonic way to do it.

- I wonder if I should refactor / have only 1 encode() and pass a flag that determines whether to have the additional allowed characters for URL fragment? Although if we’re going to have a “randomizer” as mentioned in previous paragraph, it might be good to have separate encode() functions. 

- Another thought I had was maybe to make a separate function like `domains()` to keep the function lean?

Not sure if this is all necessary. What do you think @Zac-HD?

**Comment by Zac-HD** [comment]
> This will not generate fragments that have encoded “?” and “/“ , which should still be a valid fragment —— should I put in some “randomizer” so that sometimes it encodes it and sometimes it doesn’t? Not sure if this is the Pythonic way to do it.

I'd try something like

```python
fragments = st.lists(
    st.tuples(st.characters(...), st.booleans()).map(
        lambda c: '%{c[0]:02X}' if c[1] or c[0] not in FRAGMENT_SAFE_CHARACTERS else c[0]
    ),
    min_size=1
).map("#{}".format)
```

and if you look closely, we already have `domains()` :wink:

**Comment by paxcodes** [comment]
Sorry, I misspoke. I meant a separate function for the fragments similar to `domains()`. But your code snippet there makes that unnecessary. 🤯

**Review by Zac-HD — APPROVED** [review]
Looks good - thanks @paxcodes 😍

**Pull request merged**
