### PR TITLE
Stateful Bundle support default values

### PR DESCRIPTION
**Pull request by touilleMan**
Following #321, this PR allow bundle to be pre-populated with default values.

The trick is only bundles that are defined as class attribute will be taken into account (introspection is done in the class __init__)

This PR need tests and documentation before being merged, but I wanted to get your opinion before going further ;-)

### CODE REVIEW

**Comment by DRMacIver** [comment]
Hi @touilleMan! Thanks for the contribution.

I'm not sure how I feel about the specific API though. Could you outline a particular use case you're trying to solve?

I think the use case I most commonly have with bundles is that I define some boring rule to the tune of:

```python
@rule(source=some_strategy, target=some_bundle)
def gen_v(self, source):
    return source
```

So it would be nice for this feature to remove that class of rule. Maybe the default_value argument could be a strategy instead? Then the semantics of your version could be recreated by using a `default_values=sampled_from(...)`. What do you think?

**Comment by touilleMan** [comment]
> Could you outline a particular use case you're trying to solve?

see for instance this file https://github.com/Scille/parsec-cloud/blob/54c34a3cdf69e4735e681a4ecf6c767eef57a0df/tests/hypothesis/test_core_offline_tree.py#L47

We have a file system accessible from an API and want to test creation/move/deletion of file and folders.
To do this define two bundles `Folders` and `Files` and define our rules to deal with them (e.g. rule `create_file` takes a string strategy as new file name and a `Folders` bundle as new file's directory and return a `Files` bundle.

Obviously, this means we should start the test with an empty `Files` bundle and a `Folders` bundle only containing the root (e.g. path `/`). Do to this I've created a `init_root` rule that just populate `Folders` with `/`.
The trouble is this rule is only useful once and afterward add complexity to the rules hypothesis has to deal with.
I could decorate the rule with `precondition` checking for an `initialized` flag in order to force the `init root` to be executed only once, but it's pretty cumbersome to do.

> So it would be nice for this feature to remove that class of rule. Maybe the default_value argument could be a strategy instead? Then the semantics of your version could be recreated by using a default_values=sampled_from(...). What do you think?

That seems a really cool idea !

**Comment by DRMacIver** [comment]
Thanks, that makes sense!

> The trouble is this rule is only useful once and afterward add complexity to the rules hypothesis has to deal with.

Another proposal you might find interesting is https://github.com/HypothesisWorks/hypothesis/issues/1216 which is designed for explicitly these sorts of initialization rules. The proposal doesn't currently allow for them populating bundles, but there's no reason it couldn't get a `target` argument just like `@rule` and populate a bundle that way.

This is probably a slightly simpler one to tackle than adding a default strategy to bundles, but we'd be delighted to accept (and help out with any questions you have) pull requests for either!

**Comment by Zac-HD** [comment]
Closing this in favor of #1291 - no need to wait if we all prefer that approach.

**Pull request closed without merging**
