### PR TITLE
Fix some clippy errors.

### PR DESCRIPTION
**Pull request by amw-zero**
I'm about to make a modification to `conjecture-rust` and there are currently lots of linter errors. This doesn't fix all of them, but is a start.

### CODE REVIEW

**Review by Stranger6667 — APPROVED** [review]
Looks good to me!

**Comment by Zac-HD** [comment]
Thanks for the review Dmitry!  I'm happy to merge this as a clear improvement over the status quo.

Future work:

- Zac to delete the `CODEOWNERS` entry for this, so that the two of you can merge without needing additional permissions
- Should we consider running `clippy` as well as `cargo fmt` in our CI?

**Comment by Stranger6667** [comment]
Great! 

> Should we consider running clippy as well as cargo fmt in our CI?

Yes, I think so - we can start from default settings and then move towards the `pedantic` set of lints

**Comment by Zac-HD** [comment]
I'll leave that to you in #2751 or a follow-up PR then :smile:

**Pull request merged**
