### PR TITLE
Add compatibility tests for Python 3.7

### PR DESCRIPTION
**Pull request by DRMacIver**
Hopefully this should add the Python 3.7 beta to our build matrix.

@Zac-HD can I hand over fixing #1264 in this branch to you?

### CODE REVIEW

**Comment by Zac-HD** [comment]
Hasn't quite worked yet, but very happy to take over once the 3.7 tests are running (and failing) as expected 😄

**Comment by DRMacIver** [comment]
Hm so this is unfortunate: https://github.com/travis-ci/travis-ci/issues/9069

We may not be able to support Python 3.7 on Travis. I guess we could try on CircleCI?

**Comment by DRMacIver** [comment]
I've switched it over to only running 3.7 on Circle and it seems to work, though there's something still not quite right with the build there. There are also some other tests failing (something to do with unicode) that I'll check out before handing over.

**Comment by DRMacIver** [comment]
Argh of course my *local* install *also* has Ubuntu 14, so I have to upgrade that... man these yaks are hairy.

**Comment by DRMacIver** [comment]
In theory this might be working now, but it's very fragile. It's not that I've managed to fix the SSL problems, it's that I've accidentally put it in a state where by the time it runs into them pip has already downloaded all the packages it needs and has them cached so it doesn't need to try to make an https connection at all.

I'm not very happy about this situation but I'm not really sure what we can do about it.

**Comment by DRMacIver** [comment]
Of course, the follow-on problem is that the build is passing and shouldn't be! We should be hitting #1264

**Comment by Zac-HD** [comment]
Closing this pending 3.7 support in our build tooling; I don't mind that the fancy typing stuff might not work on release day given the provisional status of everything typing-related and the amount of work required.

**Pull request closed without merging**
