### PR TITLE
Forbid to use or register `ClassVar`

### PR DESCRIPTION
**Pull request by sobolevn**
Refs #2978
Refs https://github.com/HypothesisWorks/hypothesis/pull/3201

I think that duplication is now pretty visible. Should I do something about it? 🤔

### CODE REVIEW

**Comment by sobolevn** [comment]
I can't understand why `mypy` fails. The error message seems unhelpful.

**Comment by sobolevn** [comment]
Turns out, I've just missed this tiny line in the output 😆

**Review by Zac-HD — APPROVED** [review]
Looks good to me!

**Comment by Zac-HD** [comment]
> I think that duplication is now pretty visible. Should I do something about it? 🤔

Yeah, at this point there seems to be a clear pattern.  Next time (assuming it still makes sense), let's refactor to something like

```python
for name, type_tuple in types.NON_RUNTIME_TYPES.items():
    if custom_type in type_tuple :
        raise InvalidArgument(
            f"custom_type={custom_type!r} is not allowed to be registered, "
            f"because there is no such thing as a runtime instance of {name}"
        )
```

**Pull request merged**
