### PR TITLE
unittest.subTest wrapper should be handled as method

### PR DESCRIPTION
**Pull request by fruch**
Fix: #2462

fixed as part of #europython sprints

### CODE REVIEW

**Comment by Zac-HD** [comment]
Thanks @fruch!  There are a couple of things that we need to get this working:

- Add a new file `hypothesis-python/RELEASE.rst` with the following contents:
  ```
  RELEASE_TYPE: patch

  This patch fixes :issue:`2462`, a bug in our handling of :method:`unittest.TestCase.subTest`.
  Thanks to Israel Fruchter for fixing this at the EuroPython sprints!
  ```
- Add yourself to the alphabetical list of authors in `CONTRIBUTING.rst`

and it would be nice to get a test working, though if pytest doesn't show the bug it's going to be awkward.

**Comment by fruch** [comment]
> * Add yourself to the alphabetical list of authors in `CONTRIBUTING.rst`

Done, done, and test is added.

**Comment by Zac-HD** [comment]
Note for other maintainers: I've confirmed that this actually works, and offered to write the tests for it... surprisingly tricky to get something acceptably elegant failing before and passing after *for the right reasons* rather than because of pytest magic :sweat_smile:

**Comment by Zac-HD** [comment]
@fruch - you'll need to tick the "allow edits from maintainers" box - I can't push the tests otherwise.

**Pull request merged**
