### PR TITLE
Remove one final use of md5

### PR DESCRIPTION
**Pull request by reaperhulk**
FIPS 140-2 is an obnoxious mistress, but SHA384 is a fine replacement for an MD5 even in circumstances where you don't hugely care about cryptographic security.

### CODE REVIEW

**Comment by reaperhulk** [comment]
I am hugely sympathetic to CI problems. Just let me know and I'll rebase :)

**Comment by DRMacIver** [comment]
> I am hugely sympathetic to CI problems. Just let me know and I'll rebase :)

Will do. Looks (🤞) like it's sorted now so once the CI has run on master and the release has been pushed you'll be good to go. ETA, say no more than half an hour unless something goes wrong.

**Comment by Zac-HD** [comment]
We should - though it need not be in this PR - also tighten up our Bandit config so that nobody has to remember to stay compliant. And comment in that test as to why it exists and is strict.

**Comment by DRMacIver** [comment]
You should now be able to rebase off master to get this mergeable.

**Comment by DRMacIver** [comment]
Something very strange is going on here. I don't know why the build has suddenly become flaky with this change, or whether that's a red herring. I've requeued the azure build *again* and we can keep an eye on those tests.

**Pull request merged**
