### PR TITLE
Don't consider ByteString a subclass of any Sequence.

### LINKED ISSUE #2257: Wrong data generation using dataclasses, Sequence and from_type
Hypothesis `from_type` sometimes generates bytes when the dataclass has an attribute of type `Sequence[X]`:

```python
>>> from dataclasses import dataclass
>>> from typing import Sequence
>>> @dataclass
... class Item:
...     name: str
...     

>>> @dataclass
... class Row:
...     name: str
...     items: Sequence[Item]
...     

>>> strategies.from_type(Row).example()   # <--- Wrong data type
Row(name='', items=b'\x00')

>>> strategies.from_type(Row).example()
Row(name='\x13', items=[])

>>> strategies.from_type(Row).example()
Row(name='', items=[Item(name='')])

```

### PR DESCRIPTION
**Pull request by mvaled**
Fixes #2257

### CODE REVIEW

**Comment by mvaled** [comment]
Is it OK to squash the commits?  I mean if tests pass and adding a new test for this issue.

**Comment by Zac-HD** [comment]
Squash and rebase however you like 😊

Just FYI though, I think the fix for this will actually be pretty complicated because we basically have conflicting parts of the typesystem. Or maybe requiring things to stay generic in a particular way will be enough, we'll see I guess. TLDR, very happy to review your pr but at some point I may need to take it over (preserving your author credit, of course).

**Comment by mvaled** [comment]
Hi @Zac-HD, 

I'm fairly new to the internals of hypothesis.  Do as you must to make this work.  TravisCI shows that this is in fact a far-reaching change; well beyond my current understanding.

**Comment by Zac-HD** [comment]
The issue is a high priority for me, but I'm closing this PR because I'll have to do a fair bit of experimenting to work out how to fix it.  I suspect the fix will be quite 'smeared out', and it'll certainly need a lot of tests!

**Comment by mvaled** [comment]
I'm looking forward for the new PR.  I could learn from it a lot.

**Pull request closed without merging**
