### PR TITLE
Filter internal calls from failing stateful tracebacks

### PR DESCRIPTION
**Pull request by hjtran**
I initially tried @Zac-HD suggestion of adding `__tracebackhide__ = True` but that needed to be added to every calling function in the test which seemed repetitive. Instead, I just filtered the traceback looking for instances of the `stateful.py` file name.

I added a test that I copied from `tests/pytest/test_reporting.py` and modified.

### CODE REVIEW

**Comment by hjtran** [comment]
Looks like my code is not py3 compatible. How do you guys handle code with different py2/3 syntax?

**Comment by Zac-HD** [comment]
First things first: thanks for contributing!  We may end up going back and forth a few times before merging, so I want to say at the start that we really appreciate your contribution and that you can message me any time you get stuck (whether it's trivial or huge) and I'll be happy to help out 😄 

Cross-references: this pull is related to #848 and #1170.

> Looks like my code is not py3 compatible. How do you guys handle code with different py2/3 syntax?

We always find a way to make it compatible with both 2 and 3 - either in the code itself, or by writing a wrapper (mostly in `hypothesis.internal.compat`).  In this case, I'd suggest opening `hypothesis.core` and looking at how it uses the `traceback` module - this will also show you where we have existing code that deals with exceptions.  Also note that we should avoid filtering tracebacks at all if `settings.verbosity <= Verbosity.debug`.

Since you're looking at filtering the tracebacks, I suggest looking through the comments on #848 as well.  The ideal solution is probably to write a function in `hypothesis.internal.escalation` that can be passed a traceback object, and uses `is_hypothesis_file` to filter out the bits inside Hypothesis.  You could then use that function here, and also at the relevant part of `core.py` to filter tracebacks from `@given`.

**Comment by Zac-HD** [comment]
Hi @hjtran - would you like to keep going on this PR, or would you prefer for someone else to take over?  I'd be very happy to answer any questions you have if you want to keep working on it :smile:

**Comment by hjtran** [comment]
Hey @Zac-HD , happy to keep working on this PR! I was planning on contributing on weekends but this past weekend was busy for me. Is there a preferred deadline you'd have for this>

**Comment by Zac-HD** [comment]
There's no deadline and no pressure - I just hadn't heard and wanted to check in 😄  We're perfectly happy with the "when it's ready" update schedule, and if you're working on it the issue will remain reserved for you (personally I've taken literal months before, so there really is no rush).

**Comment by Zac-HD** [comment]
Feel free to reopen this PR if or when you have an update :smile:

**Pull request closed without merging**
