### PR TITLE
strategies.uuids can generate nil uuids

### LINKED ISSUE #3263: `st.uuids()` does not generate the NIL UUID
Looking at the [`strategies.uuids()`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.uuids) code

https://github.com/HypothesisWorks/hypothesis/blob/2fbd75080015fb0f27b6d69419fbbc62d44ab739/hypothesis-python/src/hypothesis/strategies/_internal/core.py#L1618-L1639

I noticed that the [Nil UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier#Nil_UUID) is not included. It would make sense to add it into the mix, perhaps using a default argument that disables it to ensure backward compatibility, e.g.
```python
def uuids(*, version: Optional[int] = None, include_nil: bool = False) -> SearchStrategy[UUID]:
```
Happy to provide a PR, if you’re interested…

### PR DESCRIPTION
**Pull request by shlok57**
Fixes #3263

Allow `strategies.uuids` can generate nil uuids

- Contributed as a part of PyConUS2022 mentored sprint

### CODE REVIEW

**Comment by shlok57** [comment]
Coverage tests fail as tests were added to `nocover`. Will try adding relevant tests to `cover`

**Review by Zac-HD — APPROVED** [review]
Thanks @shlok57 - I've moved the test for you, and this looks great!

**Comment by jenstroeger** [comment]
Thank you both, @shlok57 and @Zac-HD for finishing this. I’m currently drowning in work, and I’m sorry I wasn’t able to contribute!

**Comment by jenstroeger** [comment]
There is a typo in the doctring:

https://github.com/HypothesisWorks/hypothesis/blob/afb0a6bed467d8b4c4a295d4cb4dccd674bc05e1/hypothesis-python/src/hypothesis/strategies/_internal/core.py#L1662-L1664

Notice that one back tick is missing after `allow_nil` which causes this render issue:

https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.uuids

Not sure if this warrants a PR 😉 But, can I? That’ll be a single-character bug fix and my first contribution! (After I didn’t manage to finish this PR…)

**Comment by Zac-HD** [comment]
Absolutely!  If we really want to avoid making a release just for that typo-fix, I can always cherry-pick it onto something else before I merge that.

If you're in a docs mood, you could even take a look at #3345 - I think maybe we just need to remove the `python:` (or whichever project) prefix in these?  Just reproducing with sphinx-build in nitpicky mode would be a great start.

**Pull request merged**
