### PR TITLE
Deprecate use of `assume` or `reject` outside of tests #3748

### PR DESCRIPTION
**Pull request by nickcollins**
If some code outside a test (e.g. `execute_example`) calls `assume` or `reject`, they raise `UnsatisfiedAssumption`, which is an internal exception that should generally not seen by user code. This branch provides a warning deprecating such use cases, which helps clarify to the user that they are getting the exception because they have called these functions from the wrong places.

A continuation of https://github.com/HypothesisWorks/hypothesis/pull/3748 because I messed up the branch on that one and had to create a new branch.

Fixes https://github.com/HypothesisWorks/hypothesis/issues/3743 and fixes https://github.com/HypothesisWorks/hypothesis/issues/3753.

### CODE REVIEW

**Comment by nickcollins** [comment]
Some of the tests are failing, including at least one of the tests I wrote, but I don't know how to read the test output to see what is wrong. Is there a way I can run the tests without adding a commit and invoking the CI?

**Comment by Zac-HD** [comment]
You can click the "details" link next to the checks below this comment, [which will lead e.g. here.](https://github.com/HypothesisWorks/hypothesis/actions/runs/6279434589/job/17055113954?pr=3751)  You can run them locally with e.g. `make format` or `make check-py310-cover`; [more details here](https://github.com/HypothesisWorks/hypothesis/blob/master/CONTRIBUTING.rst#installing-from-source-and-testing).

**Comment by Zac-HD** [comment]
...this has turned out to trigger some complicated latent issues in our engine, which are way more complicated than I anticipated.  I'll push a commit to fix that, and then merge 🚀

**Review by Zac-HD — APPROVED** [review]

**Comment by nickcollins** [comment]
Ok, thanks!

**Pull request merged**
