### PR TITLE
Initial commit of colour palette in .gpl format (GIMP palette format)

### PR DESCRIPTION
**Pull request by KathyReid**
This is a colour palette in `*.gpl` format - the GIMP palette format. 
It can be read by programs such as GIMP, Scribus and Inkscape and is submitted with the intent of making producing graphics, artwork, documents and so on for Hypothesis a little bit easier. 
Once the file is copied to the relevant area (eg. `/usr/share/inkscape/palettes` on Ubuntu 18.08 Bionic Beaver) then the palette becomes available in the application's user interface, for example, Inkscape: 
Screenshot from 2019-06-24 22-34-32

These colours were taken from the Dragonfly `svg` file by Libby Berrie. 

Feel free to reject if not required; I won't be offended in the slightest - I just really liked this colour palette :-)

### CODE REVIEW

**Comment by Zac-HD** [comment]
Nice! Can you add a description to `brand/README.rst` which covers the intended use and a brief how-to? A paragraph or so copied from the issue text, and perhaps embedding the image, would suffice!

Then very happy to merge 😁

**Comment by KathyReid** [comment]
Sure, no problem. I speak `Sphinx` / `rst` so that's easy :-)

**Comment by Zac-HD** [comment]
The images themselves are also borked on my computer 😭

**Comment by KathyReid** [comment]
Drat. Wonder if it's because I am on 4G only at the moment. Will try again, apologies for the unnecessary eyeballs. Best, K.On 25 Jun. 2019 11:54, Zac Hatfield-Dodds <notifications@github.com> wrote:The images themselves are also borked on my computer 😭

**Comment by KathyReid** [comment]
Still no good when I `git push` the files up. Will do some digging, sorry.

**Comment by KathyReid** [comment]
I *think* what's happening is that the `.gitattributes` file for Hypothesis which specifies; 
`*    text eol=lf`
is corrupting the image binary files when they are pushed up (that is, CR/LF chars are replaced with LF)

I also tried setting `git config --global core.autocrlf input`
as per https://help.github.com/en/articles/dealing-with-line-endings
then pushing the `*.png` files up again, to no avail. 

The files on my working directory are _different_ to the files that get pushed up to GitHub: 

```bash
(base) kathyreid@kathyreid-ubuntu-X510UQ:~$ diff ~/Dropbox/PHPworkspace/hypothesis/brand/inkscape.png ~/Desktop/inkscape-corrupted.png 
Binary files /home/kathyreid/Dropbox/PHPworkspace/hypothesis/brand/inkscape.png and /home/kathyreid/Desktop/inkscape-corrupted.png differ
```

```bash
(base) kathyreid@kathyreid-ubuntu-X510UQ:~$ diff ~/Dropbox/PHPworkspace/hypothesis/brand/gimp.png ~/Desktop/gimp-corrupted.png 
Binary files /home/kathyreid/Dropbox/PHPworkspace/hypothesis/brand/gimp.png and /home/kathyreid/Desktop/gimp-corrupted.png differ
```
I am going to raise a separate PR for a `.gitattributes` change that _might_ fix this (without being presumptuous :-) ) 

Best, K.

**Comment by KathyReid** [comment]
`*.png` files are still borked on `git push`. I think I might need to switch branches to `master`, do a `git pull`, then checkout this branch again so the new `.gitattributes` is honoured.

**Comment by KathyReid** [comment]
I'm going to try forking then branching from `master` again. Not sure what else to try tbh.

**Pull request closed without merging**
