### PR TITLE
Avoid caching internal strategy that has a reference to the test class

### LINKED ISSUE #493: given prevents function local types from being garbage collected
A class defined inside a function should be suitable to be garbage collected, but given prevents that. Consider the following test:

```python
 def test_local_types_are_garbage_collected():
      store = [None]

      def run_locally():
          class Test(object):
              @given(st.integers())
              def test(self, i):
                  pass
          store[0] = weakref(Test)
          Test().test()
      run_locally()
      del run_locally
      assert store[0] is not None
      gc.collect()
      assert store[0]() is None
```

This test fails, but passes if you remove the given and replace it with a normal method.

I *believe* the likely culprit is the strategy cache - I think the way we're constructing the arguments to the test function is causing something to hang on to a reference to self. This is probably a sign of a more general problem we should worry about if so.

### PR DESCRIPTION
**Pull request by Zac-HD**
For equivalent effect but better behaviour around memory use and garbage collection.  Fixes #493.

### CODE REVIEW

**Comment by Zac-HD** [comment]
Hmm, this passed on my machine.  Investigating...

**Comment by DRMacIver** [comment]
> Use id(f) instead of function as cache key 

Nooooo. 😱 😱 😱 😱 

Using id as a cache key is a source of woe and misery and nondeterministic bugs that will waste hours of your time debugging. The problem is that IDs get reused if the object is GCed. Use weakrefs.

**Comment by DRMacIver** [comment]
> Nooooo. 😱 😱 😱 😱

(If you're wondering why such a strong reaction, it's because I learned this lesson the hard way)

**Comment by DRMacIver** [comment]
> Using weakrefs kinda works... but then cache entries are dropped whenever the gc runs. That does solve the problem of things living too long, but it's not much of a cache!

Under every circumstance where using an id would do the correct thing, using a weakref does the correct thing. Perhaps the problem is that we're putting functions in cache keys at all?

**Comment by Zac-HD** [comment]
Got it!  The `(args, kwargs)` strategy created inside `@given` was also capturing a reference to the test runner, which on classes is the test class.  Avoiding caching for that one fixes our issue, and is of trivially low cost because the `kwargs` component is either cached or uncacheable.

**Comment by Zac-HD** [comment]
Now with bonus :clap: not:clap:using:clap:`id()`:clap: :stuck_out_tongue_winking_eye:

**Comment by Zac-HD** [comment]
:tada:

**Pull request merged**
