### PR TITLE
Fix pytest plugin issue

### PR DESCRIPTION
**Pull request by jobh**
See https://github.com/HypothesisWorks/hypothesis/pull/3837#issuecomment-1894791471

This fixes the spurious warning in pytest's tests by not incrementing the `in_initialization` counter in the `pytest_configure` hook, only at import time. The decrement in `pytest_sessionstart` is called as normal before every test session, so we allow the variable to go negative.

### CODE REVIEW

**Comment by jobh** [comment]
I get failure on win3.10. Looks unrelated, but is consistent in two test runs.
```
FAILED hypothesis-python/tests/nocover/test_sampled_from.py::test_filter_large_lists[100000] - hypothesis.errors.Flaky: Inconsistent data generation! Data generation behaved differently between different runs. Is your data generation depending on external state?
FAILED hypothesis-python/tests/nocover/test_sampled_from.py::test_filter_large_lists[1000000] - hypothesis.errors.Flaky: Inconsistent data generation! Data generation behaved differently between different runs. Is your data generation depending on external state?
FAILED hypothesis-python/tests/nocover/test_sampled_from.py::test_filter_large_lists[33554432] - hypothesis.errors.Flaky: Inconsistent data generation! Data generation behaved differently between different runs. Is your data generation depending on external state?
```

**Comment by jobh** [comment]
I forgot
> I also noticed that the warning unconditionally mentions "import time", we should be specific about import time / between import and loading the pytest plugin / during pytest initialization.

which can go into this PR, or another. To separate these cases will require a bit of infra, probably adding a global to record the loading stage. You ok with that?

**Comment by Zac-HD** [comment]
Yeah, I'm OK with adding some more calls to ensure that our messages are as accurate and informative as possible.

PR looks good to me, though I don't have time to investigate that flake at the moment 😅

**Comment by jobh** [comment]
Oops, I pushed the wrong button and edited your message instead of quote-replying it. My bad! Sorry!

**Comment by jobh** [comment]
> PR looks good to me, though I don't have time to investigate that flake at the moment 😅

Me neither, but I went as far as seeing that `nocover/test_sampled_from.py::test_filter_large_lists` is flaky because it has an `assert` inside its filter predicate, and that it should probably be removed because the same assert would trigger a bit later in a non-flaky way. I'll do that now in the hope that it gives more information about the underlying problem.

**Review by Zac-HD — APPROVED** [review]
Added a nocover annotation to the "at import time" branch, manually confirmed that it fires when expected to and added a comment, let's ship it 🚀 

And again, thank you _so much_ for following up so quickly, and dealing with all the unrelated stuff that happens along the way ❤️

**Pull request merged**
