### PR TITLE
Fix typing issue under Python 3.5.0

### LINKED ISSUE #2095: AttributeError: module 'typing' has no attribute '_Final' (or '_Union')
Traceback (most recent call last):
  File "/tmpfs/bazel_tests_virtualenv/lib/python3.5/site-packages/hypothesis/internal/compat.py", line 304, in <module>
    typing_root_type = (typing._Final, typing._GenericAlias)  # type: ignore
AttributeError: module 'typing' has no attribute '_Final'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmpfs/tmp/bazel/sandbox/linux-sandbox/725/execroot/tensorflow_probability/bazel-out/k8-opt/bin/tensorflow_probability/python/bijectors/bijector_properties_test_eager.runfiles/tensorflow_probability/tensorflow_probability/python/bijectors/bijector_properties_test.py", line 23, in <module>
    import hypothesis as hp
  File "/tmpfs/bazel_tests_virtualenv/lib/python3.5/site-packages/hypothesis/__init__.py", line 27, in <module>
    from hypothesis._settings import (
  File "/tmpfs/bazel_tests_virtualenv/lib/python3.5/site-packages/hypothesis/_settings.py", line 40, in <module>
    from hypothesis.internal.compat import integer_types, quiet_raise, string_types
  File "/tmpfs/bazel_tests_virtualenv/lib/python3.5/site-packages/hypothesis/internal/compat.py", line 310, in <module>
    typing._Union,
AttributeError: module 'typing' has no attribute '_Union'

### PR DESCRIPTION
**Pull request by Zac-HD**
Closes #2095.

### CODE REVIEW

**Comment by Zac-HD** [comment]
CC @brianwa84.

**Comment by brianwa84** [comment]
Looks good to me, thanks!

**Comment by alexwlchan** [comment]
No test?

**Comment by Zac-HD** [comment]
Existing tests catch this, so we'd have to add a whole new CI job and I didn't think it worth the trouble. No objection if you'd like to set one up though!

**Comment by alexwlchan** [comment]
Nah, if you’re happy then so am I.

I’m just hoping you don’t invalidate the data in this graph *that I made today for a presentation I’m giving tomorrow evening*: https://twitter.com/alexwlchan/status/1174721788896534528/photo/1

😝

**Comment by Zac-HD** [comment]
Approving review then? It's only one release, it'll hardly show...

**Pull request merged**
