### PR TITLE
refactor(tests): Move slow moving tests to tests/nocover

### PR DESCRIPTION
**Pull request by CuriousLearner**
Some work on issue #852.

### CODE REVIEW

**Comment by Zac-HD** [comment]
This looks fantastic - just [one last formatting change!](https://travis-ci.org/HypothesisWorks/hypothesis/jobs/421391569#L1045)

**Comment by Zac-HD** [comment]
... would you mind if I try to get the formatting working and push that?

**Comment by Zac-HD** [comment]
FYI @CuriousLearner there are some other build issues I'm working through; this is top of the stack after that's dealt with though :smile:

**Comment by CuriousLearner** [comment]
Wow! Thanks @Zac-HD 🎉

**Comment by Zac-HD** [comment]
Thank *you!*

After I worked out the problem in #1528, the flaky test here was suddenly obvious: replaying examples from the database was (only when testing Hypothesis itself) the wrong thing to do here, and empty lists were pointless to test.  So I tried adding `database=None` to the settings and it worked :smile:

**Comment by Zac-HD** [comment]
You certainly could move more tests - the issue is still open! - but I'd suggest picking something else and coming back later if you're still keen.

- #1547 is a nice self-contained change, improving dev experience with better messages
- #1388 improves Django integeration - write a simple strategy and add the hooks
- any other issue you think looks interesting!

**Comment by CuriousLearner** [comment]
Awesome! I'll have a look at those. Thanks!

**Pull request merged**
